# **Sesión 3: Procesamiento Avanzado de Imágenes** ⚙️🖼️

## **Librerías**

In [13]:
import cv2
import os
import copy 
import imageio
from typing import List
import numpy as np

## **Apartado B:** Detección de lineas rectas
El objetivo de este apartado es la detección de líneas y bordes en las imágenes de la carpeta `data`.
1. **Tarea B.1.** Aplique `cv2.Canny()` a las imágenes de trabajo ajustando los hiperparámetros.
3. **Tarea B.2.** Implemente la función `draw_lines()` para pintar las líneas sobre las imágenes.
4. **Tarea B.3.** Aplique Hough con `cv2.HoughLinesP()` a las imágenes de trabajo para extraer líneas y afine los hiperparámetros.
5. **Problema B.1.** Repita el procedimiento para extraer las líneas de las dos imágenes restantes.

### **NOTA**
Podéis usar el mismo formato de guardado de resultados y nomenclatura que en partA o hacer uso de la funcion `show_image()` del Lab 2. Usad las herramientas con las que os sintáis más cómodos

In [14]:
import glob

# This initial part is to highlight that cv2.imshow() and cv2.imwrite() works well with previous BGR conversion
def imageio_load_images(filenames):
    '''
    Load images using imageio.imread function (RGB)
    '''
    return [imageio.imread(filename) for filename in filenames]

def opencv_load_images(filenames):
    '''
    Load images cv2.imread function (BGR)
    '''
    return [cv2.imread(filename) for filename in filenames]

# TODO Create two sorted lists with the paths of all images in the data/source folder using glob
source_paths = sorted(glob.glob("../data/source/*"))

# Cargar las imágenes utilizando ambas funciones
imageio_images = imageio_load_images(source_paths)
opencv_images = opencv_load_images(source_paths)

C:\Users\Jose Juan\AppData\Local\Temp\ipykernel_44728\3303442465.py:8: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  return [imageio.imread(filename) for filename in filenames]


### **Tarea B.1.** Aplique `cv2.Canny()` a las imágenes de trabajo ajustando los hiperparámetros

In [15]:
# TODO Apply canny to the images, play with the thresholds to get a good result


destination_folder = "../data/partB"
edge_imgs = []  # to store the canny edge images for later Hough transform

# 1st image

# Hyperparameters
low_threshold = 50  
high_threshold = 150

# get the first image
img1_path = "../data/source/0.jpg"
img1 = cv2.imread(img1_path)

# Convert to grayscale
gray_img = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)

# Apply Canny edge detection
edge_img = cv2.Canny(gray_img, low_threshold, high_threshold)

# Store the edge image for later Hough transform
edge_imgs.append(edge_img)

# Display the image or save it as you like
cv2.imwrite(os.path.join(destination_folder, "Canny_Edge_1.jpg"), edge_img)

# 2nd image

# Hyperparameters
low_threshold = 70
high_threshold = 200

# get the first image
img2_path = "../data/source/1.png"
img2 = cv2.imread(img2_path)

# Convert to grayscale
gray_img = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# Apply Canny edge detection
edge_img = cv2.Canny(gray_img, low_threshold, high_threshold)

# Store the edge image for later Hough transform
edge_imgs.append(edge_img)

# Display the image or save it as you like
cv2.imwrite(os.path.join(destination_folder, "Canny_Edge_2.jpg"), edge_img)

True

### **Tarea B.2.** Implemente `draw_lines()` para pintar las lineas sobre cada imagen

In [16]:
# TODO Draw the lines on the images. A line is a tuple of 4 integers (x1, y1, x2, y2) where (x1, y1) and (x2, y2) are the coordinates of the two points of the line.
def draw_lines(img, lines, color=(0, 255, 0), thickness=2):
    for line in lines:
        x1, y1, x2, y2 = line[0]
        cv2.line(img, (x1, y1), (x2, y2), color, thickness)
    return img

### **Tarea B.3.** Aplique Hough con `cv2.HoughLinesP()` a las imágenes de trabajo para extraer líneas y afine los hiperparámetros

In [17]:
# TODO Apply the hough transform to the images, play with the parameters to get a good result
import numpy as np
# 1st image

# Define the hough transform parameters
rho = 1                 
theta = np.pi / 180
threshold = 50          
min_line_length = 30    
max_line_gap = 10


# Apply the hough transform
lines_img1 = cv2.HoughLinesP(edge_imgs[0], rho, theta, threshold, minLineLength=min_line_length, maxLineGap=max_line_gap)

original_img1 = cv2.imread("../data/source/0.jpg")  # Asegúrate de que esta ruta sea correcta
img_with_lines1 = draw_lines(original_img1.copy(), lines_img1, color=(255, 0, 0), thickness=3)  # Color rojo, grosor 3

# Show the image or save it as you like
cv2.imwrite(os.path.join(destination_folder, "Hough_Transform_Image_1.jpg"), img_with_lines1)

# 2nd image
rho = 1                 
theta = np.pi / 180
threshold = 50          
min_line_length = 30    
max_line_gap = 10



# Apply the hough transform
lines_img1 = cv2.HoughLinesP(edge_imgs[1], rho, theta, threshold, minLineLength=min_line_length, maxLineGap=max_line_gap)
original_img1 = cv2.imread("../data/source/1.png")  # Asegúrate de que esta ruta sea correcta
img_with_lines1 = draw_lines(original_img1.copy(), lines_img1, color=(255, 0, 0), thickness=3)  # Color rojo, grosor 3

# Show the image or save it as you like
cv2.imwrite(os.path.join(destination_folder, "Hough_Transform_Image_2.jpg"), img_with_lines1)

True

### **Problema B.1.** Repita el procedimiento para extraer las líneas de las dos imágenes restantes

In [18]:
def show_image(img: np.array, img_name: str = "Image"):
    cv2.imshow(img_name, img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [19]:
# TODO Homework
# TODO Apply canny to the images, play with the thresholds to get a good result


# 3rd image
img = opencv_images[2]

# Hyperparameters
low_threshold = 60
high_threshold = 200

# Convert to grayscale
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Apply Canny edge detection
edge_img = cv2.Canny(img, low_threshold, high_threshold)

# Store the edge image for later Hough transform
edge_imgs.append(edge_img)

# Display the image or save it as you like
show_image(edge_img)



# get the fourth image
img = opencv_images[3]

# Hyperparameters
low_threshold = 60
high_threshold = 230

# Convert to grayscale
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Apply Canny edge detection
edge_img = cv2.Canny(img, low_threshold, high_threshold)

# Store the edge image for later Hough transform
edge_imgs.append(edge_img)

# Display the image or save it as you like
show_image(edge_img)

# 3rd image (opencv_images[2])
# Define the hough transform parameters
rho = 1
theta = np.pi / 180
threshold = 50
min_line_length = 20
max_line_gap = 2

# Get the edge image for the 3rd image
edges = edge_imgs[2]

# Apply the hough transform
lines = cv2.HoughLinesP(edges, rho, theta, threshold, min_line_length, max_line_gap)
print(lines)

# Draw the lines on the image (on the original image, make sure to get a deep copy to avoid modifying the original)
img_with_lines = draw_lines(copy.deepcopy(opencv_images[2]), lines, (0, 255, 0), thickness=3)

# Show the image or save it as you like
show_image(img_with_lines)

# 4th image (opencv_images[3])
rho = 1
theta = np.pi/180
threshold = 25
min_line_length = 5
max_line_gap = 35

# Get the edge image for the 4th image
edges = edge_imgs[3]

# Apply the hough transform
lines = cv2.HoughLinesP(edges, rho, theta, threshold, min_line_length, max_line_gap)
print(lines)

# Draw the lines on the image (on the original image, make sure to get a deep copy)
img_with_lines = draw_lines(copy.deepcopy(opencv_images[3]), lines, (0, 255, 0), thickness=3)

# Show the image or save it as you like
show_image(img_with_lines)


[[[451 497 644 497]]

 [[655 637 655  15]]

 [[515 360 647 360]]

 ...

 [[ 38 426  71 426]]

 [[249 426 305 426]]

 [[482 117 485 114]]]
[[[ 61 226 289 226]]

 [[ 66 250 284 250]]

 [[ 61  66 165  66]]

 [[ 63  39 287  39]]

 [[291  64 519  64]]

 [[415 224 519 224]]

 [[289 223 289  67]]

 [[519 223 519 146]]

 [[521 252 521  38]]

 [[290 144 413 144]]

 [[291 224 291 145]]

 [[292 146 413 146]]

 [[167 224 167 146]]

 [[ 58 252  58  39]]

 [[165 224 165  67]]

 [[ 61 224  61 146]]

 [[413 223 413 147]]

 [[415 223 415  66]]

 [[207  64 263  64]]

 [[337 226 393 226]]

 [[ 77  64 133  64]]

 [[418 226 474 226]]

 [[156  64 206  64]]

 [[168 224 288 224]]

 [[290  66 412  66]]

 [[413 136 413  80]]

 [[420  39 476  39]]

 [[291  67 291 114]]

 [[300 250 348 250]]

 [[ 61  97  61 144]]

 [[358 250 414 250]]

 [[519 101 519  66]]

 [[299  39 355  39]]

 [[418 250 474 250]]

 [[167  72 167 128]]

 [[191 144 232 144]]

 [[ 95 224 151 224]]

 [[416  66 465  66]]

 [[519 144 519 102]]

 [[4